### ISSUE TITLE
How do you visualize the feature?

### ISSUE THREAD

**Issue by AtlantixJJ** [huawei-noah/AdderNet#1]
Hi, thanks for your brilliant work. However, I didn't find details of how you visualize the high dimensional feature of neural network. Do you visualize the entire last feature map with shape (N, C, H, W), or the average pooled feature map, or the last layer before classification? Which visualization method do you use?

**Comment by HantingChen** [comment]
We train a LeNet++ on the MNIST dataset, which have six convolutional layers and a fully-connected layer.  Numbers of neurons in each convolutional layer are 32, 32, 64,64, 128, 128, and 2, respectively. 

The features with 2 dimension are used for visualization. The detailed code can be referred on https://github.com/jxgu1016/MNIST_center_loss_pytorch/blob/master/MNIST_with_centerloss.py
