### ISSUE TITLE
Why the paper does not provide the training/inference time or speed experiment results?

### ISSUE THREAD

**Issue by machanic** [huawei-noah/AdderNet#11]
I read your paper, but I cannot find the speed test experiments, why not test?

**Comment by HantingChen** [comment]
Since we do not implement cuda and cudnn acclearation for addernet for now, the speed will not be faster than convolution with cuda and cudnn.

**Comment by KindleHe** [comment]
> Since we do not implement cuda and cudnn acclearation for addernet for now, the speed will not be faster than convolution with cuda and cudnn.

Then, what about your inference time on cpu, compared other sota models ?

**Comment by HantingChen** [comment]
> 
> 
> > Since we do not implement cuda and cudnn acclearation for addernet for now, the speed will not be faster than convolution with cuda and cudnn.
> 
> Then, what about your inference time on cpu, compared other sota models ?

I'm sorry that we have not compared with other sota models.
