### ISSUE TITLE
the speed of adder.adder2d slower than torch.nn.Conv2d ? I'm confused.

### ISSUE THREAD

**Issue by zccyman** [huawei-noah/AdderNet#13]
I replace adder.adder2d with torch.nn.Conv2d, and replace torch.cdist with [my_cdist](https://github.com/pytorch/pytorch/issues/15253). train my network, the speed of the new model slower than the old at least 6 times. I'm confused.

```
@torch.jit.script
def my_cdist(x1, x2):
    x1_norm = x1.pow(2).sum(dim=-1, keepdim=True)
    x2_norm = x2.pow(2).sum(dim=-1, keepdim=True)
    res = torch.addmm(x2_norm.transpose(-2, -1), x1, x2.transpose(-2, -1), alpha=-2).add_(x1_norm)
    res = res.clamp_min_(1e-30).sqrt_()

    return res
```

**Comment by HantingChen** [comment]
nn.conv2d is acclerated by using cuda and cudnn, which is defintely faster than the adder2d without cuda accleration.

**Comment by zccyman** [comment]
@HantingChen Thanks! I want to know how many times the adder2d with cuda accleration faster than nn.conv2d ?

**Comment by HantingChen** [comment]
> 
> 
> @HantingChen Thanks! I want to know how many times the adder2d with cuda accleration faster than nn.conv2d ?

Since the speed of 32bit multiplications and additions in GPU are almost the same, adder and conv will take almost the same time if with cuda accleration

**Comment by promach** [comment]
@zccyman Do you have idea about using [YOLOv3 together with AdderNet](https://github.com/huawei-noah/AdderNet/issues/16#issuecomment-615863100) ?
