### ISSUE TITLE
Modify YOLOv3 backbone from DarkNet to AdderNet

### ISSUE THREAD

**Issue by promach** [huawei-noah/AdderNet#16]
How to correctly modify https://github.com/eriklindernoren/PyTorch-YOLOv3 to use https://github.com/huawei-noah/AdderNet ?

The following [colab ipynb notebook](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-yolov3_-_addernet-ipynb) is what I have so far with the helps of others:

https://colab.research.google.com/drive/1VCafwykgNKAO6144LssBFFy0TmruDNSE#scrollTo=W3e-WcVxnKfs

How to solve the error on this [models.py](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-models-py-L321) file ?

![addernet_error](https://user-images.githubusercontent.com/3324659/79001970-12d2ef00-7b82-11ea-9e2f-8c0f98fd0852.png)

```
Namespace(batch_size=8, class_path='data/coco.names', conf_thres=0.001, data_config='config/coco.data', img_size=416, iou_thres=0.5, model_def='config/yolov3.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    model.load_darknet_weights(opt.weights_path)
  File "/content/PyTorch-YOLOv3/models.py", line 321, in load_darknet_weights
    num_w = conv_layer.weight.numel()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'adder2d' object has no attribute 'weight'
```

**Comment by HantingChen** [comment]
'adder2d' object has no attribute 'weight', you may change the definition of self.adder with self.weight in class adder2d.

**Comment by promach** [comment]
@summeryumyee 

You should use [modification](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-adder-py-L75) in the following class : 

```
class adder2d(nn.Module):

    def __init__(self,input_channel,output_channel,kernel_size, stride=1, padding=0, bias = False):
        super(adder2d, self).__init__()
        self.stride = stride
        self.padding = padding
        self.input_channel = input_channel
        self.output_channel = output_channel
        self.kernel_size = kernel_size
        self.adder = torch.nn.Parameter(nn.init.normal_(torch.randn(output_channel,input_channel,kernel_size,kernel_size)))
        self.bias = bias
        if bias:
            self.b = torch.nn.Parameter(nn.init.uniform_(torch.zeros(output_channel)))

    def forward(self, x):
        output = adder2d_function(x,self.adder, self.stride, self.padding)
        if self.bias:
            output += self.b.unsqueeze(0).unsqueeze(2).unsqueeze(3)
        
        return output
```

**Comment by promach** [comment]
@HantingChen 

The difference between the [original models.py](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/models.py) and [modified models.py](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-models-py) is the root cause of [GPU out-of-memory runtime error](https://github.com/huawei-noah/AdderNet/issues/6#issuecomment-613362421).

```
def conv2d(in_channels, out_channels, kernel_size, stride, padding, bias):
    """3x3 or 1x1 convolution with padding"""
    return adder.adder2d(in_channels, out_channels, kernel_size=kernel_size, stride=stride,
                     padding=padding, bias=bias)
```

**Comment by promach** [comment]
@HantingChen What is the purpose of the [following code snippet](https://github.com/huawei-noah/AdderNet/blob/master/resnet20.py#L67-L71) ?

```
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                adder.adder2d(self.inplanes, planes * block.expansion, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(planes * block.expansion)
            )
```

**Comment by summeryumyee** [comment]
@promach 
Thank you for your answer. I'll try it now.

**Comment by promach** [comment]
@GZQ0723 

According to AdderNet paper theoretical explanation about smaller gradient with respect to filters and [the use of adaptive learning rate as the countermeasure solution](https://arxiv.org/pdf/1912.13200.pdf#page=5) to this problem and [the explanation on new_cdist() function](https://stackoverflow.com/a/61229485) , 

the back-propagation equation for AdderNet had already included the concept of [adaptive learning rate](https://github.com/promach/PyTorch-YOLOv3/blob/addernet/adder.py#L34).  

So, I still do not understand why training AdderNet requires significantly more GPU memory ?

**Comment by promach** [comment]
@ranery @HantingChen @GZQ0723 See https://discuss.pytorch.org/t/understanding-cdist-function/76296/8 and the also the rest of the replies.

**Comment by HantingChen** [comment]
> @HantingChen What is the purpose of the [following code snippet](https://github.com/huawei-noah/AdderNet/blob/master/resnet20.py#L65-L79) ?
> 
> ```
>     def _make_layer(self, block, planes, blocks, stride=1):
>         downsample = None
>         if stride != 1 or self.inplanes != planes * block.expansion:
>             downsample = nn.Sequential(
>                 adder.adder2d(self.inplanes, planes * block.expansion, kernel_size=1, stride=stride, bias=False),
>                 nn.BatchNorm2d(planes * block.expansion)
>             )
> 
>         layers = []
>         layers.append(block(inplanes = self.inplanes, planes = planes, stride = stride, downsample = downsample))
>         self.inplanes = planes * block.expansion
>         for _ in range(1, blocks):
>             layers.append(block(inplanes = self.inplanes, planes = planes))
> 
>         return nn.Sequential(*layers)
> ```

It is the definition of ResNet.

**Comment by HantingChen** [comment]
> @ranery @HantingChen @GZQ0723 See https://discuss.pytorch.org/t/understanding-cdist-function/76296/8 and the also the rest of the replies.

If you want to train AdderNet, I sincerely suggest that you should imply cuda version for AdderNet instead of trying to write new cdist function. Cuda version of AdderNet will largely speed up the training and reduce the memory usage.

**Comment by promach** [comment]
@HantingChen What do you exactly mean by **cuda version of AdderNet** ?

Since AdderNet currently does not provide backward propagation code for training purpose, @ranery coded the [backward propagation](https://github.com/huawei-noah/AdderNet/issues/6#issuecomment-594212162) `new_cdist()` which includes the `torch.cdist()` function.

**Comment by HantingChen** [comment]
> @HantingChen What do you exactly mean by **cuda version of AdderNet** ?
> 
> Since AdderNet currently does not provide backward propagation code for training purpose, @ranery coded the [backward propagation](https://github.com/huawei-noah/AdderNet/issues/6#issuecomment-594212162) `new_cdist()` which includes the `torch.cdist()` function.

You can refer to https://pytorch.org/tutorials/advanced/cpp_extension.html.

**Comment by promach** [comment]
@HantingChen  

You mean using the C++ extension of PyTorch as shown below ?

```
std::vector<torch::Tensor> lltm_backward(
    torch::Tensor grad_h,
    torch::Tensor grad_cell,
    torch::Tensor new_cell,
    torch::Tensor input_gate,
    torch::Tensor output_gate,
    torch::Tensor candidate_cell,
    torch::Tensor X,
    torch::Tensor gate_weights,
    torch::Tensor weights) {
  auto d_output_gate = torch::tanh(new_cell) * grad_h;
  auto d_tanh_new_cell = output_gate * grad_h;
  auto d_new_cell = d_tanh(new_cell) * d_tanh_new_cell + grad_cell;

  auto d_old_cell = d_new_cell;
  auto d_candidate_cell = input_gate * d_new_cell;
  auto d_input_gate = candidate_cell * d_new_cell;

  auto gates = gate_weights.chunk(3, /*dim=*/1);
  d_input_gate *= d_sigmoid(gates[0]);
  d_output_gate *= d_sigmoid(gates[1]);
  d_candidate_cell *= d_elu(gates[2]);

  auto d_gates =
      torch::cat({d_input_gate, d_output_gate, d_candidate_cell}, /*dim=*/1);

  auto d_weights = d_gates.t().mm(X);
  auto d_bias = d_gates.sum(/*dim=*/0, /*keepdim=*/true);

  auto d_X = d_gates.mm(weights);
  const auto state_size = grad_h.size(1);
  auto d_old_h = d_X.slice(/*dim=*/1, 0, state_size);
  auto d_input = d_X.slice(/*dim=*/1, state_size);

  return {d_old_h, d_input, d_weights, d_bias, d_old_cell};
}
```

**Comment by HantingChen** [comment]
> @HantingChen
> 
> You mean using the C++ extension of PyTorch as shown below ?
> 
> ```
> std::vector<torch::Tensor> lltm_backward(
>     torch::Tensor grad_h,
>     torch::Tensor grad_cell,
>     torch::Tensor new_cell,
>     torch::Tensor input_gate,
>     torch::Tensor output_gate,
>     torch::Tensor candidate_cell,
>     torch::Tensor X,
>     torch::Tensor gate_weights,
>     torch::Tensor weights) {
>   auto d_output_gate = torch::tanh(new_cell) * grad_h;
>   auto d_tanh_new_cell = output_gate * grad_h;
>   auto d_new_cell = d_tanh(new_cell) * d_tanh_new_cell + grad_cell;
> 
>   auto d_old_cell = d_new_cell;
>   auto d_candidate_cell = input_gate * d_new_cell;
>   auto d_input_gate = candidate_cell * d_new_cell;
> 
>   auto gates = gate_weights.chunk(3, /*dim=*/1);
>   d_input_gate *= d_sigmoid(gates[0]);
>   d_output_gate *= d_sigmoid(gates[1]);
>   d_candidate_cell *= d_elu(gates[2]);
> 
>   auto d_gates =
>       torch::cat({d_input_gate, d_output_gate, d_candidate_cell}, /*dim=*/1);
> 
>   auto d_weights = d_gates.t().mm(X);
>   auto d_bias = d_gates.sum(/*dim=*/0, /*keepdim=*/true);
> 
>   auto d_X = d_gates.mm(weights);
>   const auto state_size = grad_h.size(1);
>   auto d_old_h = d_X.slice(/*dim=*/1, 0, state_size);
>   auto d_input = d_X.slice(/*dim=*/1, state_size);
> 
>   return {d_old_h, d_input, d_weights, d_bias, d_old_cell};
> }
> ```

cuda extension

**Comment by promach** [comment]
This line of code : `auto d_gates = torch::cat({d_input_gate, d_output_gate, d_candidate_cell}, /*dim=*/1);` contains contiguous call which will consume excessive GPU memory.

**Comment by HantingChen** [comment]
> This line of code : `auto d_gates = torch::cat({d_input_gate, d_output_gate, d_candidate_cell}, /*dim=*/1);` contains contiguous call which will [consume excessive GPU memory](https://github.com/pytorch/pytorch/issues/37408).

This is a example to tell you how to use cuda extension in pytorch, not the implementation of cdist.

**Comment by promach** [comment]
@ranery

Please have a look at the dimension of some of the tensor variables in your back-propagation function implementation.

```
@staticmethod
def backward(ctx, grad_output):
    W, X = ctx.saved_tensors
    print("W size= ", W.size())
    print("X size= ", X.size())
    grad_W = grad_X = None
    if ctx.needs_input_grad[0]:
        _temp1 = torch.unsqueeze(X, 2).expand(X.shape[0], X.shape[1], W.shape[0]).permute(1, 0, 2)
        _temp2 = torch.unsqueeze(W.transpose(0, 1), 1)
        print("_temp1 size= ", _temp1.size())
        print("_temp2 size= ", _temp2.size())
        _temp = fast_cdist(_temp1, _temp2, p).squeeze().transpose(0, 1)
        print("_temp size= ", _temp.size())
        grad_W = torch.matmul(grad_output, _temp)
        print("grad_W size= ", grad_W.size())
        print('before norm: ', torch.norm(grad_W))
        grad_W = eta * np.sqrt(grad_W.numel()) / torch.norm(grad_W) * grad_W
        print('after norm: ', torch.norm(grad_W))
        print("grad_W size= ", grad_W.size())
    if ctx.needs_input_grad[1]:
        _temp1 = torch.unsqueeze(W, 2).expand(W.shape[0], W.shape[1], X.shape[0]).permute(1, 0, 2)
        _temp2 = torch.unsqueeze(X.transpose(0, 1), 1)
        _temp = fast_cdist(_temp1, _temp2, p).squeeze().transpose(0, 1)
        _temp = torch.nn.functional.hardtanh(_temp, min_val=-1., max_val=1.)
        grad_X = torch.matmul(grad_output.transpose(0, 1), _temp)
    return grad_W, grad_X
```


```
W size=  torch.Size([75, 256])
X size=  torch.Size([3872, 256])
_temp1 size=  torch.Size([256, 3872, 75])
_temp2 size=  torch.Size([256, 1, 75])
_temp size=  torch.Size([3872, 256])
grad_W size=  torch.Size([75, 256])
before norm:  tensor(nan, device='cuda:0')
after norm:  tensor(nan, device='cuda:0')
grad_W size=  torch.Size([75, 256])
W size=  torch.Size([256, 1152])
X size=  torch.Size([3872, 1152])
_temp1 size=  torch.Size([1152, 3872, 256])
_temp2 size=  torch.Size([1152, 1, 256])
Traceback (most recent call last):
  File "train.py", line 112, in <module>
    scaled_loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 4.25 GiB (GPU 0; 5.93 GiB total capacity; 2.94 GiB already allocated; 1.83 GiB free; 3.15 GiB reserved in total by PyTorch)
```

**Comment by promach** [comment]
`_temp1 = torch.unsqueeze(X, 2).expand(X.shape[0], X.shape[1], W.shape[0]).permute(1, 0, 2)`

how can we re-write this line of code using lesser memory ?

**Comment by promach** [comment]
@HantingChen Using [CUDA version of AdderNet](https://github.com/promach/PyTorch-YOLOv3/blob/addernet/YOLOv3_+_AdderNet.ipynb) from https://github.com/jdnie/AdderNetCuda also resulted in out-of-memory error with `batch_size = 8` for a 16GB GPU. Something is still not right.

**Comment by promach** [comment]
It seems that the OOM error is gone for now by using [Apex opt_level="02"](https://nvidia.github.io/apex/amp.html#opt-levels).

But training time is still too slow, the loss is too large to converge.

As a result, only TWO (2) out of 100 training epochs could finish in 10 hours.

Any advices ?

Note: I am already using a small VOC2017 dataset and `batch_size = 8` for training.

**Comment by promach** [comment]
@jdnie 

I was using https://github.com/jdnie/AdderNetCuda in [YOLOv3 training](https://github.com/huawei-noah/AdderNet/issues/16#issuecomment-624408420).

However, every epochs take too much time to finish. Do you have any idea why ?
