### ISSUE TITLE
 Train own data set

### ISSUE THREAD

**Issue by hehaiyang111** [huawei-noah/AdderNet#22]
hi，
How does transfer learning train its own data set to modify pre-training parameters?
thanks

**Comment by HantingChen** [comment]
Maybe you can refer to https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html.

**Comment by hehaiyang111** [comment]
![image](https://user-images.githubusercontent.com/53802041/86535284-d3face00-bf11-11ea-9e24-044ed09f335c.png)
![image](https://user-images.githubusercontent.com/53802041/86535302-f4c32380-bf11-11ea-9d12-40421788c5a6.png)
but，
![image](https://user-images.githubusercontent.com/53802041/86535319-12908880-bf12-11ea-97a4-189ec58aacf6.png)
acc  0.1 +
why?
Thanks bro.

**Comment by hehaiyang111** [comment]
Is the pre-trained model trained on ImageNet or other？

**Comment by HantingChen** [comment]
The pre-trained ResNet-50 is trained on ImageNet. 

Maybe batchsize 4 is too small to train a model. We use 256 batchsize to train our AdderNet on ImageNet.
