### ISSUE TITLE
Equation (5) - partial derivative of the Euclidean norm

### ISSUE THREAD

**Issue by andgitchang** [huawei-noah/AdderNet#24]
Hi,
I would like to know why you defined the L2-distance as in Equation (14) appendix.
Doesn't L2-distance need a square root outside the summations?
And also, I would like to know how the corresponding partial derivative of L2-distance in Equation (5) comes?
Thanks.

**Comment by HantingChen** [comment]
We define the L2-distance to further investigate different metrics in neural networks. We still use L1 distance in AdderNets.

The partial derivative of L2-distance uses its originial derivative .

**Comment by andgitchang** [comment]
I know you use L1 distance in forward pass and full-precision L2 derivative in backward optimization.
But my question is 

1. Considering L2 distance (see [Definition](https://en.wikipedia.org/wiki/Euclidean_distance)), don't we need an extra sqrt outside the summations of Eq.(14) in your CVPR2020 [supp](https://openaccess.thecvf.com/content_CVPR_2020/supplemental/Chen_AdderNet_Do_We_CVPR_2020_supplemental.pdf)?
2. Following the [def](https://en.wikipedia.org/wiki/Euclidean_distance) of L2 distance, shouldn't its derivative Eq.(5) in AdderNets be like \partial ||x||_2 = x / ||x||_2 ? (please refer to p-norm subsection under [Examples](https://en.wikipedia.org/wiki/Norm_(mathematics)#Examples))

If I have misunderstood anything, please correct me. Thanks.

**Comment by HantingChen** [comment]
1. Yes, so we finally use the L1-AdderNet in our main paper. The L2-AdderNet is proposed only for investigation.

2. We use the L2^2 distance in fact, as defined in our supp.

**Comment by andgitchang** [comment]
Thanks for your detailed explanation
