### ISSUE TITLE
multiplication-free for only forward pass? Training is multiplication intense.

### ISSUE THREAD

**Issue by CJYLab** [huawei-noah/AdderNet#25]
Hi there,

I have noticed that there are still plenty of multiplication operations in the backward pass and even square roots are required.
Is your method only multiplication free in forward pass but costly in training?
Thank you,

**Comment by HantingChen** [comment]
Yes. Most applications for computer vision focus on the inference of networks, since the training procedure can be conducted using GPUs.

**Comment by CJYLab** [comment]
Thank you Hanting,
Your research is interesting. I will follow up your work.
