### ISSUE TITLE
Could you give other pre-trained models?

### ISSUE THREAD

**Issue by SoyeonUm** [huawei-noah/AdderNet#29]
Hello, 

Thank you for sharing your code.

I want to inference about cifar100 and Imagenet. 

But the pre-trained models you were upload are only about cifr10-renet20, Imagenet-resnet50.

It takes too long to learn.

Could you give a trained model for cifar100 using resnet20 and ImageNet using resnet18?

Thank you :)

**Comment by HantingChen** [comment]
Sure, these pre-tained models will be released in a few weeks or months.
