### ISSUE TITLE
加法网络参数量和flops计算

### ISSUE THREAD

**Issue by CLC0530** [huawei-noah/AdderNet#38]
您好，可以提供加法网络的参数量和flops的计算公式吗？

**Comment by HantingChen** [comment]
你好，加法网络的参数量/FLOPs和相同结构的CNN是一样的。FLOPs代表的是加法和乘法运算次数之和，加法网络只是将CNN中乘法换为加法，总的运算次数是一样的。

关于CNN的计算公式可以自行查阅资料。
