### ISSUE TITLE
Look Forward of Codes about AdderSR

### ISSUE THREAD

**Issue by LiuzhuForFun** [huawei-noah/AdderNet#39]
Hi,
Thanks for this excellenct work!
I cannot find the project page (detailed codes) of AdderSR: Towards Energy Efficient Image Super-Resolution

**Comment by HantingChen** [comment]
Thanks for your attention. The code of AdderSR has not been released.

**Comment by rushirajsherlocked** [comment]
Ya AdderNet for Super Resolution would be pretty interesting to look upon! @HantingChen When would be the code released :/ ??
