### ISSUE TITLE
度量方式选择

### ISSUE THREAD

**Issue by CLC0530** [huawei-noah/AdderNet#40]
您好，卷积网络使用的是互相关度量，加法网络使用的是曼哈顿度量，请问这两种度量方式有没有从理论上可以推导的优劣之分？或者说两种度量方式是不是针对不同的场景有各自的优势？或者说为什么加法网络在准确率上会略低于卷积网络？

**Comment by HantingChen** [comment]
我们正在进行加法网络相关的理论分析。目前看来，加法网络的准确率可能由于优化方法等原因会低于卷积网络，我们也正在寻求方法进一步提升加法网络准确率。

**Comment by CLC0530** [comment]
谢谢您的回复，并祝您元旦快乐，对于前面那个问题，我还想问下有没有可能是因为选择了不同的相似性度量方式，导致的性能降低？比如我看到有一些文章中针对某些特定任务会将CNN网络提取到特征，再次投影到曼哈顿距离上。

**Comment by HantingChen** [comment]
> 谢谢您的回复，并祝您元旦快乐，对于前面那个问题，我还想问下有没有可能是因为选择了不同的相似性度量方式，导致的性能降低？比如我看到有一些文章中针对某些特定任务会将CNN网络提取到特征，再次投影到曼哈顿距离上。

也有可能，不同的度量可能适合于不同的任务。
