### ISSUE TITLE
BatchNorm 效果不好

### ISSUE THREAD

**Issue by zhangruiidol2013** [huawei-noah/AdderNet#41]
您好，看了您的文章，感觉非常好，最近也结合项目，将Conv替换了Adder ，但是我发现貌似BatchNorm 针对某些场景并不好。针对这个咱们有啥替换的建议不？？谢谢。

**Comment by HantingChen** [comment]
你好，可以尝试替换为其他norm，例如layernorm，instancenorm，groupnorm等

**Comment by zhangruiidol2013** [comment]
对，我现在替换了 groupnorm . 期待会有好的结果。谢谢您。
