### ISSUE TITLE
AdderNet for SR

### ISSUE THREAD

**Issue by leiwen83** [huawei-noah/AdderNet#42]
Hi,

I see recent you have applying addernet for EDSR quantization, which is a great work.
But for some other SR, like EDVR, using deformable conv for the frame alignment.

I wonder whether addernet also be efficient, or even can be applied to this kind of network?
Since the DCNv2 using in EDVR is a irregular conv, how to adjust quantization int8 loss introduced by adderNet?
Do you have some thought over this kind of op?

Thx,
Lei

**Comment by HantingChen** [comment]
We have not try to replace the deformable conv by adder operation. AdderNet can also be efficient for this kind of network if successfully applied. 

For the int8 quantization, we use the post-quantization (no retrain, no loss) and you may refer to https://arxiv.org/pdf/2101.10015 for more information.
