### ISSUE TITLE
Adder layer实现反卷积问题？

### ISSUE THREAD

**Issue by MillionLee** [huawei-noah/AdderNet#45]
你好，请问一下adder layer是否可以实现反卷积呢？我尝试用adder layer实现反卷积来实现上采样两倍，但是最后输出的尺寸确是两倍少一，我想应该是outputpadding那里有问题，所以想请教您一下该如何做呢

**Comment by HantingChen** [comment]
你好，可以参考conv的反卷积实现，将conv的计算替换为adder计算即可。
