### ISSUE TITLE
您好，我想咨询一下ImageProcessingTransformer的问题

### ISSUE THREAD

**Issue by jiaaihhy** [huawei-noah/AdderNet#46]
您好，冒昧打扰。 之前拜读了您团队的Pretrained ImageProcessingTransformer， 受益匪浅。在尝试复现您的论文，但是在Dataloader和Datasets的写过程中遇到了问题。不知如何裁剪图片， 如何对数据进行预处理。论文中提到Overlap10Pix， 但是边缘部分如何处理！  
若能分享解惑，不甚感激。
感谢感谢，期待回复。

**Comment by HantingChen** [comment]
你好，IPT相关代码请参考：
https://gitee.com/mindspore/mindspore/tree/master/model_zoo/research/cv/IPT

**Comment by jiaaihhy** [comment]
感谢您的回复！
我想问一下，IPT做超分，finetune的时候使用的数据集还是ImageNet吗， 还是在Div2k或者哪个数据集上进行的finetune！
期待您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/AdderNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huawei-noah/AdderNet] 您好，我想咨询一下ImageProcessingTransformer的问题 (#46)





 
你好，IPT相关代码请参考：
 https://gitee.com/mindspore/mindspore/tree/master/model_zoo/research/cv/IPT

**Comment by HantingChen** [comment]
在DIV2K上进行的finetune，相关问题请移步IPT的github，谢谢
