### ISSUE TITLE
计算方差公式的疑问

### ISSUE THREAD

**Issue by Lg955** [huawei-noah/AdderNet#48]
论文中公式8和公式9可以那么计算的前提是“X”中以及“F”中每个位置像素独立同分布吗? ( 如果不是的话怎么得出来公式8和9的?）

![image](https://user-images.githubusercontent.com/69025725/116332747-e3cb0200-a804-11eb-87c3-7a97c5d85dea.png)
![image](https://user-images.githubusercontent.com/69025725/116332757-ecbbd380-a804-11eb-8adc-763acd462342.png)

**Comment by HantingChen** [comment]
是的

**Comment by Lg955** [comment]
> 是的

谢谢您！
