### ISSUE TITLE
adder 反卷积

### ISSUE THREAD

**Issue by MillionLee** [huawei-noah/AdderNet#51]
你好，请问反卷积若也用adder来实现的话，是否可以像反卷积那样适合图像重构任务呢？

**Comment by HantingChen** [comment]
可以，反卷积也是卷积的一种，只需要同样把反卷积中的乘法替换为加法和绝对值操作即可。

**Comment by MillionLee** [comment]
你好，我按照卷积和反卷积的操作，将反卷积中的卷积操作替换成了adder，但是可视化中间的特征图为啥会出现比较严重的块效应。这是什么原因呢？感谢您的解答！
![image](https://user-images.githubusercontent.com/68136466/123281799-8de0b500-d53c-11eb-9df4-aac7c78cb2c0.png)

**Comment by HantingChen** [comment]
你好，如果是CNN会出现这种现象吗？
