### ISSUE TITLE
AdderNet模型量化

### ISSUE THREAD

**Issue by myzhuang** [huawei-noah/AdderNet#55]
AdderNet模型量化
请问一下AdderNet模型的int8量化代码是否有打算开源？如果不方便的话，能否说一下
AdderNet and Its Minimalist Hardware Design for Energy-Efficient Artificial Intelligence
量化部分参考的论文/代码？
我们发现模型训练出来的权重范围比ConvNet大比较多，大约-7~6，以往的量化方法使用起来不是那么适合。
谢谢！

**Comment by HantingChen** [comment]
不打算开源，量化算法部分可以参考论文3.1节，谢谢！
