### ISSUE TITLE
L2 to L1 training scheme

### ISSUE THREAD

**Issue by jdsjfi** [huawei-noah/AdderNet#58]
Hello, the L2 to L1 training scheme presented in your paper is interesting, but I have some questions. In the paper, it says, "p is linearly reduced from 2 to 1", what does it mean? Does it mean that p is linearly reduced from 2 to 1 with respect to each epoch or each step? Thanks very much!!!

**Comment by HantingChen** [comment]
Yes

**Comment by jdsjfi** [comment]
Sorry, I think you may have misunderstood what I mean. I reproduce L2 to L1 training scheme by reducing p for each step. I want to know whether my apprach is correct. Thank you very much!

**Comment by HantingChen** [comment]
p is reduced for each epoch, but I think it also works if you reduce it for each step.

**Comment by MillionLee** [comment]
thanks for your respond!
