### ISSUE TITLE
RuntimeError: _cdist_backward requires X2 to be contiguous

### ISSUE THREAD

**Issue by ranery** [huawei-noah/AdderNet#6]
Hi, I am trying to train your addernet, but it returns me one runtime error, which I supposed attributes to `.continuous()` function or some other uncommon operations used in your `adder.py`.

Could you help to solve this issue?

**Comment by HantingChen** [comment]
The provided code is used only for inference. If you want to train the addernet, you can refer https://github.com/huawei-noah/AdderNet/issues/5#issuecomment-593755574 to write a function to replace the cdist.

**Comment by ranery** [comment]
Hi, hanting chen, thanks for your reply.

I have tried to customize the `cdist` function, it works but suffers from several problems:
- It incurs gradient vanishing, i.e., `torch.norm(grad_W)` will decrease to 0 after three or four iterations.
- Could you show the hyper-parameter setting of `eta`, which I suppose is critical for adjusting local learning rate.
- It remains EXTREMELY slow (e.g., over 10 mins for single epoch if using resnet20@cifar10)! Any idea to boost the speed?

**Comment by ranery** [comment]
Hi, hanting chen, thanks for your reply.

I have tried to customize the cdist function, it works back-propogation but suffers from several problems now:

- The loss remain much similar during training.
- Could you show the hyper-parameter setting of eta, which I suppose is critical for adjusting local learning rate.
- It remains EXTREMELY slow (e.g., over 15 mins for single epoch if using resnet20@cifar10)! Any idea to boost the speed?

Could you give some suggestions for working the training? Thanks in advance for your time.

Below is my implementation FYI:
````
def new_cdist(p, eta):
    class cdist(torch.autograd.Function):
        @staticmethod
        def forward(ctx, W, X):
            ctx.save_for_backward(W, X)
            out = -torch.cdist(W, X, p)
            return out

        @staticmethod
        def backward(ctx, grad_output):
            W, X = ctx.saved_tensors
            grad_W = grad_X = None
            if ctx.needs_input_grad[0]:
                _temp1 = torch.unsqueeze(X, 2).expand(X.shape[0], X.shape[1], W.shape[0]).permute(1, 0, 2)
                _temp2 = torch.unsqueeze(W.transpose(0, 1), 1)
                _temp = - torch.cdist(_temp1, _temp2, p).squeeze().transpose(0, 1)
                grad_W = torch.matmul(grad_output, _temp)
                # print('before norm: ', torch.norm(grad_W))
                grad_W = eta * np.sqrt(grad_W.numel()) / torch.norm(grad_W) * grad_W
                print('after norm: ', torch.norm(grad_W))
            if ctx.needs_input_grad[1]:
                _temp1 = torch.unsqueeze(W, 2).expand(W.shape[0], W.shape[1], X.shape[0]).permute(1, 0, 2)
                _temp2 = torch.unsqueeze(X.transpose(0, 1), 1)
                _temp = - torch.cdist(_temp1, _temp2, p).squeeze().transpose(0, 1)
                _temp = torch.nn.functional.hardtanh(_temp, min_val=-1., max_val=1.)
                grad_X = torch.matmul(grad_output.transpose(0, 1), _temp)
            return grad_W, grad_X
    return cdist().apply
````

**Comment by HantingChen** [comment]
I try to run your code, but it returns the error:

   _temp = torch.cdist(_temp1, _temp2, 1).squeeze().transpose(0, 1)
 RuntimeError: cdist only supports 2D tensors, X1 got: 3D

So I cannot find whether your code have any problem.

The eta is set as 0.2 for ResNet-20 on CIFAR-10.  

The inference of AdderNets is slow since the adder filters is implemented by torch.cdist. You can write cuda for the adder module (as matmul on cuda) to achieve higher inference speed.

**Comment by ranery** [comment]
Thanks for your reply and suggestions!

The return error attributes to the pytorch version. I use the default latest version v1.4.0, I just found that is the only branch supporting 3D `cdist`. Sorry for the inconvenience and could you please run it again?

**Comment by HantingChen** [comment]
I'm sorry that it would be hard for me to update the Pytorch version. So I manually check the code.

There may be some mistake in the following code:

**Comment by ranery** [comment]
Thanks!

**Comment by sher2018** [comment]
> Thanks!

Could you share your train code?:D

**Comment by promach** [comment]
@ranery how do we use [your new cdist function](https://github.com/huawei-noah/AdderNet/issues/6#issuecomment-594212162) in our own training code ?

Here is [AdderNet training code using YOLOv3](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-yolov3_-_addernet-ipynb) in which I am also facing the same cdist runtime error as you were

**Comment by promach** [comment]
Ok, I have [solved the above cdist error](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-yolov3_-_addernet-ipynb)

**Comment by promach** [comment]
@ranery I have modified the [adder.py](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33/2f452c29a64fa84e602977faa54d55a0873638dd#file-adder-py-L31) according to your suggestion. 

However, it seems that your `cdist` modification had increased GPU memory usage by a lot.

Please advise.

```
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/content/PyTorch-YOLOv3/adder.py", line 31, in backward
    _temp = torch.cdist(_temp1, _temp2, p).squeeze().transpose(0, 1)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 671, in cdist
    return torch._C._VariableFunctions.cdist(x1, x2, p, None)
RuntimeError: CUDA out of memory. Tried to allocate 5.06 GiB (GPU 0; 11.17 GiB total capacity; 2.26 GiB already allocated; 4.66 GiB free; 6.14 GiB reserved in total by PyTorch)
```

**Comment by promach** [comment]
@HantingChen Does trainng adderNet actually consume a lot of GPU memory ? At one instance, I seen GPU out-of-memory error of 9GB which is insane.

Note: I have already adjusted the values of batch_size and subdivisions for many times, yet I still could not eliminate the GPU out-of-memory error. 

Could you advise ?

**Comment by HantingChen** [comment]
> 
> 
> @HantingChen Does trainng adderNet actually consume a lot of GPU memory ? At one instance, I seen GPU out-of-memory error of 9GB which is insane.
> 
> Note: I have already adjusted the values of batch_size and subdivisions for many times, yet I still could not eliminate the GPU out-of-memory error.
> 
> Could you advise ?

That is related to your implementation. Theoretically the GPU comsumption of AdderNet is the same as that of CNN with same architecture.

**Comment by promach** [comment]
@HantingChen I only implemented [new_cdist()](https://github.com/huawei-noah/AdderNet/issues/6#issuecomment-594212162) in [YOLOv3](https://github.com/eriklindernoren/PyTorch-YOLOv3) by replacing the multiplication inside the [convolution](https://gist.github.com/promach/8ddd9794f242c24ffdaa612bcb0bfa33#file-models-py-L16-L19) with addition.

**Comment by promach** [comment]
@ranery I saw there are two `cdist()` implementations online ([code 1](https://github.com/pytorch/pytorch/pull/25799#issuecomment-529021810) , [code 2](https://github.com/pytorch/pytorch/issues/15253#issuecomment-491467128))

```
def fast_cdist(x1, x2):
    adjustment = x1.mean(-2, keepdim=True)
    x1 = x1 - adjustment
    x2 = x2 - adjustment  # x1 and x2 should be identical in all dims except -2 at this point

    # Compute squared distance matrix using quadratic expansion
    # But be clever and do it with a single matmul call
    x1_norm = x1.pow(2).sum(dim=-1, keepdim=True)
    x1_pad = torch.ones_like(x1_norm)
    x2_norm = x2.pow(2).sum(dim=-1, keepdim=True)
    x2_pad = torch.ones_like(x2_norm)
    x1_ = torch.cat([-2. * x1, x1_norm, x1_pad], dim=-1)
    x2_ = torch.cat([x2, x2_pad, x2_norm], dim=-1)
    res = x1_.matmul(x2_.transpose(-2, -1))

    # Zero out negative values
    res.clamp_min_(1e-30).sqrt_()
    return res
```

```
import time
import torch


@torch.jit.script
def my_cdist(x1, x2):
    x1_norm = x1.pow(2).sum(dim=-1, keepdim=True)
    x2_norm = x2.pow(2).sum(dim=-1, keepdim=True)
    res = torch.addmm(x2_norm.transpose(-2, -1), x1, x2.transpose(-2, -1), alpha=-2).add_(x1_norm)
    res = res.clamp_min_(1e-30).sqrt_()
    return res


a = torch.randn(10000, 9).cuda()
b = torch.randn(30000, 9).cuda()

for i in range(5):
    start_time = time.time()
    res = torch.cdist(a, b)
    torch.cuda.synchronize()
    print(f'torch cdist time {i}: {time.time() - start_time:.2f}s')

for i in range(5):
    start_time = time.time()
    res2 = my_cdist(a, b)
    torch.cuda.synchronize()
    print(f'my cdist time {i}: {time.time() - start_time:.2f}s')
```

**Comment by promach** [comment]
@ranery Could you advise more about https://github.com/huawei-noah/AdderNet/issues/16#issuecomment-615863100 in which `conv2d()` is the root cause instead of `cdist()` ?

**Comment by promach** [comment]
@ranery 

What are `_temp1` and `_temp2` for ?

```
                _temp1 = torch.unsqueeze(X, 2).expand(X.shape[0], X.shape[1], W.shape[0]).permute(1, 0, 2)
                _temp2 = torch.unsqueeze(W.transpose(0, 1), 1)
                _temp = torch.cdist(_temp1, _temp2, p).squeeze().transpose(0, 1)
```

**Comment by ranery** [comment]
> @ranery Could you advise more about [#16 (comment)](https://github.com/huawei-noah/AdderNet/issues/16#issuecomment-615863100) in which `conv2d()` is the root cause instead of `cdist()` ?

This is because when calculating the gradient and error, current pytorch-based solution considers unfolding to collect and subtract corresponding block of both the feature map and weight filter, leading to unnecessary memory consumption, I suppose the way they use in their paper is cuda version which directly convolute through the feature map, in which way the memory consumption is normal (similar to multiplication-based convolution networks).

**Comment by promach** [comment]
> current pytorch-based solution considers unfolding to collect and subtract corresponding block of both the feature map and weight filter, leading to unnecessary memory consumption

Could you elaborate in terms of `_temp1` and `_temp2` ?

```
_temp1 = torch.unsqueeze(X, 2).expand(X.shape[0], X.shape[1], W.shape[0]).permute(1, 0, 2)
_temp2 = torch.unsqueeze(W.transpose(0, 1), 1)
_temp = torch.cdist(_temp1, _temp2, p).squeeze().transpose(0, 1)
```

**Comment by kamalojasv181** [comment]
@promach how to generalise these to any value of p?
