### ISSUE TITLE
关于固定加法核进行加法运算

### ISSUE THREAD

**Issue by ldk-97** [huawei-noah/AdderNet#65]
你好，我想固定加法核进行加法替代卷积的操作。
我把生成的核 tensor 直接放在 output = adder2d_function(x, self.adder, self.stride, self.padding) 的 self.adder 中，发现效果和固定卷积核操作相差甚远，不知道是因为加法核和卷积核的分布差异导致还是其他原因，想咨询一下作者有固定加法核进行加法操作的方法吗？谢谢

**Comment by HantingChen** [comment]
你好，请问你说的“固定卷积核”具体是指？

神经网络（不管是加法还是乘法）通常需要进行训练以达到较好的效果。

**Comment by ldk-97** [comment]
> 你好，请问你说的“固定卷积核”具体是指？
> 
> 神经网络（不管是加法还是乘法）通常需要进行训练以达到较好的效果。

**Comment by ldk-97** [comment]
谢谢回复！我可以通过固定卷积核进行卷积达到类似于滤波的效果，看到这篇文章后我就咨询一下能不能通过固定加法核进行加法运算？
