### ISSUE TITLE
VGG-small

### ISSUE THREAD

**Issue by ldk-97** [huawei-noah/AdderNet#68]
请问文章里用到的VGG-small是一个怎样的网络模型？

**Comment by HantingChen** [comment]
可以参考https://github.com/microsoft/LQ-Nets/blob/master/cifar10-vgg-small.py

**Comment by ldk-97** [comment]
> 可以参考https://github.com/microsoft/LQ-Nets/blob/master/cifar10-vgg-small.py

谢谢！还想请问一下文章用的LeNet-5-BN的网络格式？我按照原始的LeNet-5加BN层，导出的网络运算量只有215K的乘法和215K的加法，并达不到文章所说的435K的乘法和加法运算量。望解答，谢谢~

**Comment by HantingChen** [comment]
采用的是最经典的LeNet-5网络结构：http://yann.lecun.com/exdb/publis/pdf/lecun-01a.pdf

![image](https://user-images.githubusercontent.com/40243544/159611540-1c657acc-51d1-4cda-861f-4250cbc91d96.png)
