### ISSUE TITLE
The first conv layer is not add operation

### ISSUE THREAD

**Issue by ranery** [huawei-noah/AdderNet#7]
Hi, I find that you use multiplication-based kernel to conduct first layer feature extraction in both `resnet20.py` and `resnet50.py`:
````
self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False)
````
Is it a special trick or I can directly replace it with adder layer without accuracy drop?

**Comment by HantingChen** [comment]
It is a usual practice for model compression to keep the first conv layer. You can replace it with adder layer with a very small accuracy drop.

**Comment by ranery** [comment]
I see, thanks.
