### ISSUE TITLE
Negative Sign in L1 Distance Equation

### ISSUE THREAD

**Issue by aliarastehfard** [huawei-noah/AdderNet#72]
![image](https://user-images.githubusercontent.com/49977238/217644512-50facf6f-18aa-4065-845d-c00b9fe0c05f.png)

Hi! I wonder where did this negative sign come from?

**Comment by HantingChen** [comment]
It is introduced to ensure that if X and F are more similar, the output Y will be larger, which is same as that in CNN.

**Comment by uranusx86** [comment]
> It is introduced to ensure that if X and F are more similar, the output Y will be larger, which is same as that in CNN.

I don't get it. Adding a negative sign just changes the sign, it makes the value even smaller!

**Comment by HantingChen** [comment]
> > It is introduced to ensure that if X and F are more similar, the output Y will be larger, which is same as that in CNN.
> 
> I don't get it. Adding a negative sign just changes the sign, it makes the value even smaller!

Sry for the misleading. As the output will have a bias, we only pay attention to the 'relative' value of different inputs. For example, if F is more similar with X1 than X2, than the output Y1 should be larger than X2.

**Comment by uranusx86** [comment]
It's clear to me now. Thank you!

**Comment by aliarastehfard** [comment]
Thanks! I'm closing the issue.
